drop DATABASE IF EXISTS bookweb;

create DATABASE IF NOT EXISTS bookweb;

USE bookweb;

CREATE TABLE GoiDocSach (
 ID INT NOT NULL,
 TenGoiDoc VARCHAR(50),
 GiaTri INT,
 ThoiLuong INT,
 MoTa VARCHAR(255)
);

ALTER TABLE GoiDocSach ADD CONSTRAINT PK_GoiDocSach PRIMARY KEY (ID);


CREATE TABLE NguoiDung (
 ID INT NOT NULL,
 TenDN VARCHAR(50) NOT NULL,
 MatKhau VARCHAR(50) NOT NULL,
 Email VARCHAR(50) NOT NULL,
 SoDienThoai VARCHAR(50),
 DiemTichLuy INT,
 URL VARCHAR(255),
 VaiTro VARCHAR(50)
);

ALTER TABLE NguoiDung ADD CONSTRAINT PK_NguoiDung PRIMARY KEY (ID);


CREATE TABLE Sach (
 ID INT NOT NULL,
 TenSach VARCHAR(50),
 TrangThai VARCHAR(50),
 TacGia VARCHAR(50),
 NgayHoanThanh DATE,
 NgaySangTac DATE DEFAULT CURRENT_TIMESTAMP,
 SoChuong INT,
 URLBiaSach VARCHAR(255),
 GiaSach INT,
 TheLoai VARCHAR(50),
 MoTa VARCHAR(1024)
);

ALTER TABLE Sach ADD CONSTRAINT PK_Sach PRIMARY KEY (ID);


CREATE TABLE TuSach (
 ID INT NOT NULL,
 NguoiDungID INT NOT NULL,
 SoLuongSach INT
);

ALTER TABLE TuSach ADD CONSTRAINT PK_TuSach PRIMARY KEY (ID);


CREATE TABLE ChiTietTuSach (
 TuSachID INT NOT NULL,
 SachID INT NOT NULL,
 NgayThem DATE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ChiTietTuSach ADD CONSTRAINT PK_ChiTietTuSach PRIMARY KEY (TuSachID,SachID);


CREATE TABLE Chuong (
 ID INT NOT NULL,
 SachID INT NOT NULL,
 TenChuong VARCHAR(50),
 ChiSoChuong INT,
 NoiDung TEXT NOT NULL
);

ALTER TABLE Chuong ADD CONSTRAINT PK_Chuong PRIMARY KEY (ID);


CREATE TABLE MuaGoiDoc (
 ID INT NOT NULL,
 NguoiDungID INT NOT NULL,
 GoiDocSachID INT NOT NULL,
 NgayMua DATE DEFAULT CURRENT_TIMESTAMP,
 NgayHetHan DATE
);

ALTER TABLE MuaGoiDoc ADD CONSTRAINT PK_MuaGoiDoc PRIMARY KEY (ID);


CREATE TABLE MuaSach (
 NguoiDungID INT NOT NULL,
 SachID INT NOT NULL,
 NgayMua DATE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE MuaSach ADD CONSTRAINT PK_MuaSach PRIMARY KEY (NguoiDungID,SachID);

ALTER TABLE MuaGoiDoc
  AUTO_INCREMENT = 1;

ALTER TABLE Chuong
  AUTO_INCREMENT = 1;

ALTER TABLE TuSach
  AUTO_INCREMENT = 1;
  
ALTER TABLE Sach
  AUTO_INCREMENT = 1;

ALTER TABLE NguoiDung
  AUTO_INCREMENT = 1;

ALTER TABLE GoiDocSach
  AUTO_INCREMENT = 1;




ALTER TABLE TuSach ADD CONSTRAINT FK_TuSach_0 FOREIGN KEY (NguoiDungID) REFERENCES NguoiDung (ID);


ALTER TABLE ChiTietTuSach ADD CONSTRAINT FK_ChiTietTuSach_0 FOREIGN KEY (TuSachID) REFERENCES TuSach (ID);
ALTER TABLE ChiTietTuSach ADD CONSTRAINT FK_ChiTietTuSach_1 FOREIGN KEY (SachID) REFERENCES Sach (ID);


ALTER TABLE Chuong ADD CONSTRAINT FK_Chuong_0 FOREIGN KEY (SachID) REFERENCES Sach (ID);


ALTER TABLE MuaGoiDoc ADD CONSTRAINT FK_MuaGoiDoc_0 FOREIGN KEY (NguoiDungID) REFERENCES NguoiDung (ID);
ALTER TABLE MuaGoiDoc ADD CONSTRAINT FK_MuaGoiDoc_1 FOREIGN KEY (GoiDocSachID) REFERENCES GoiDocSach (ID);


ALTER TABLE MuaSach ADD CONSTRAINT FK_MuaSach_0 FOREIGN KEY (NguoiDungID) REFERENCES NguoiDung (ID);
ALTER TABLE MuaSach ADD CONSTRAINT FK_MuaSach_1 FOREIGN KEY (SachID) REFERENCES Sach (ID);


